project:
  type: website
  output-dir: _site

website:
  title: "Estadística IV"
  site-url: https://benjaminbaeza.github.io/stadisticawebfinal/
  
  navbar:
    right:
      - href: programa.qmd
        text: Programación
      - text: Clases
        menu:
          - text: "Modulo 1 · Presentación del curso"
            href: Modulos/clase1.qmd
       


      - text: Prácticos
        menu:
          - text: "Práctico 1 Nociones basicas de Rstudios: Exploración y Preparación de Bases de Datos"
            href: Practicos/Practico1.qmd
          - text: "Práctico 2: Chi-cuadrado; Tablas de contingencia y Analisis de Correspondecia Simple (ACS)
            href: Practicos/Practico2.qmd

                    
      - text: Ayudantia
        menu:
          - text: "Ayudantia"
            href: Ayudantiass/Ayudantia1.qmd




        
      

format:
  html:
    theme: cosmo
    toc: true
    toc-location: right
    toc-title: "En esta página"
    smooth-scroll: true
    css: styles.css

