---
title: "Módulo 2 · Análisis exploratorio"
format: html
editor: visual
css: styles.css
---

::: callout-note
**Fecha:** martes 20 de agosto
:::

## Objetivos de la sesión

-   Introducción al análisis exploratorio
-   Tipos de variables

## Presentación

📄 [Ver presentación (PDF)](../clases/clase_20_agosto.pdf){target="_blank"}

````{=html}
<div class="pdf-container" style="border: 1px solid #ddd; border-radius: 5px; margin: 20px 0;">
<embed src="../clases/clase_20_agosto.pdf" 
       type="application/pdf" 
       width="100%" 
       height="650px" />
</div>

## Práctico 1

 **En este práctico deberá replicar la primera parte del ejercicio trabajado en el Módulo 2: Creación de tablas de contingencia y cálculo e interpretación de Chi-cuadrado (X²), utilizando una base de datos distinta, a elección del estudiante.**

El desarrollo debe considerar los siguientes pasos:

- Seleccionar una base de datos propia (puede utilizar bases disponibles en repositorios abiertos o las sugeridas por el curso).

- Construir una tabla de contingencia entre dos variables categóricas.

- Calcular el estadístico Chi-cuadrado (X²) de forma manual (puede apoyarse en calculadora, Excel, R u otro medio).

- Registrar el cálculo manual mediante una fotografía del procedimiento.

- Calcular el estadístico Chi-cuadrado (X²) en R y comparar ambos resultados.

- Utilizar la tabla de distribución Chi-cuadrado para interpretar el resultado obtenido.

- Redactar una interpretación sustantiva del resultado en función de las variables analizadas.

Finalmente, el ejercicio debe subirse al buzón de Tareas de U-Campus.
Si el trabajo está correctamente realizado, **se otorgarán 2 décimas adicionales para el próximo control.**

---

## Lecturas asociadas

- Aldás, Joaquín y Uriel, Ezequiel (2017). 
Capítulo 5  - "Correspondence Analysis” 

---
