---
title: "Módulo 1 · Presentación del curso"
format: html
editor: visual
css: styles.css
---

::: callout-note
**Fecha:** martes 13 de agosto
:::

## Objetivos de la sesión

En esta clase se espera que el estudiantado sea capaz de:

-   Conocer la estructura general del curso.
-   Comprender los objetivos de aprendizaje.
-   Familiarizarse con la dinámica de trabajo y evaluaciones.

------------------------------------------------------------------------

## Documento de presentación

 [Ver presentación (PDF)](../clases/clase_13_agosto.pdf){target="_blank"}

````{=html}
<div class="pdf-container" style="border: 1px solid #ddd; border-radius: 5px; margin: 20px 0;">
<embed src="../clases/clase_13_agosto.pdf" 
       type="application/pdf" 
       width="100%" 
       height="650px" />
</div>

**Ejercicio:**
Arme grupos de 2 a 3 personas: 

- Explore la base (dimensión)

- Renombrar las variables con nombres breves y generar etiquetas
(para cada variable.)

- Identificar valores perdidos y darles un valor o eliminar los casos

- Identificar casos outliers y ver qué se hace con esos casos

- Identifique las variables que requieren codificación y proponga
categorías y asigne valores.

- Identifique las variables nominales, ordinales, continuas y de razón.

- Proponga preguntas de investigación que se puedan responder
con estas variables.

- Explore la base mediante tablas de frecuencia y tablas de
contingencia.

---

## Lecturas asociadas

- Lectura 1: Introducción al análisis exploratorio.
- Lectura 2: Uso de R en investigación social.

